name: Run Azure Alerts Export Script
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Remote_execution/requirements.txt

    - name: Run Script
      run: python ./Remote_execution/Azure-Export-Alerts.py
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ALERT_PATTERN: "${{ vars.ALERT_PATTERN }}"
        SUBSCRIPTION_PATTERN: "${{ vars.SUBSCRIPTION_PATTERN }}"
        EXCEL_FILE_NAME: "${{ vars.EXCEL_FILE_NAME }}"

    - name: Rename output file
      run: mv ./Remote_execution/output_dir/${{ vars.EXCEL_FILE_NAME }}.xlsx ./Remote_execution/output_dir/${{ vars.EXCEL_FILE_NAME }}-${{ github.run_number }}.xlsx

    - name: Upload Alert File as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: azure-alerts-artifact
        path: ./Remote_execution/output_dir/${{ vars.EXCEL_FILE_NAME }}-${{ github.run_number }}.xlsx