name: RunDolarBlue

on:
  workflow_dispatch:  # Se ejecuta a demanda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Instalar la versión de Python

      - name: Install Python packages
        run: |
          cd Others  # Cambiar al directorio donde se encuentra requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: |
          cd Others  # Cambiar al directorio donde se encuentra dolarBlue.py
          python dolarBlue.py
